### ISSUE TITLE
server install - old install_linux.txt?

### ISSUE THREAD

**Issue by M4D1S0N** [philipcwhite/Monitoring#1]
Hi,

is install_linux.txt outdated? try to setup the server. can't find these files. tried to execute ./mserver but nothing works.
imported monitoring.sql manually. tables can be found with mysql.

start.py -> webserver is running. if I want to login with "admin" and "password" -> auth failure

sudo python3 start.py 
METHOD:GET
PATH:/login
EXT:html
ARGUMENTS:
COOKIE:CookieAuth=%5Bnull%2C%22%242y%2410%24lDDINIqB8IE%5C%2FMzijCurq1ua6x9QwbFG.E5HH2BYxlOhf%5C%2FVSSl8eji%22%5D
SESSION_ID:CookieAuth=%5Bnull%2C%22%242y%2410%24lDDINIqB8IE%5C%2FMzijCurq1ua6x9QwbFG.E5HH2BYxlOhf%5C%2FVSSl8eji%22%5D

atal error: protocol.data_received() call failed.
protocol: <web.server.web_handle object at 0x7f302d477550>
transport: <_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 860, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/home/susradm/monitoring/server/web/server.py", line 249, in data_received
    if reply is None: reply = self.call_controller()
  File "/home/susradm/monitoring/server/web/server.py", line 207, in call_controller
    for x in parsed_args: args.append(x.split('=')[1])
IndexError: list index out of range

**Comment by philipcwhite** [comment]
It probably was outdated.  I know I made some changes with the python version when I jumped from 3.7 to 3.8.  I may have had the admin create script disabled as well.  Sorry for the late response.
